const translations = {
   en: {
      "nav.home": "Home",
      "nav.ww2": "Holocaust & WWII",
      "nav.hollywood": "Icons & Culture",
      "footer.slogan": ["History that shapes ", "Tomorrow"],
      "footer.founderTitle": "Founder & Director | Cain Archive",
      "footer.coordinatorTitle": "Institutional & Archive Coordinator | Cain Archive",
      "footer.founderEmail": "john@cainarchive.com",
      "footer.founderPhone": "+1 561 884 0648",
      "footer.coordinatorEmail": "dina.kriukova@cainarchive.com",
      "footer.copyright": "© 2025 Cain Archive. All Rights Reserved.",
      "footer.protectedText": "Original vintage photographs are displayed for documentary, educational, and research purposes. Cain Archive holds physical ownership of the original prints but does not claim copyright to the underlying images. Unauthorized reproduction or commercial use is prohibited.",
      "fullscreenMenu.home": "Home",
      "fullscreenMenu.ww2": "Holocaust & WWII",
      "fullscreenMenu.hollywood": "Icons & Culture",
      "fullscreenMenu.contactFounderTitle": "Founder & Director | Cain Archive",
      "fullscreenMenu.contactEmail": "john@cainarchive.com",
      "fullscreenMenu.contactPhone": "+1 561 884 0648",
      "fullscreenMenu.contactCoordinatorTitle": "Institutional & Archive Coordinator | Cain Archive",
      "fullscreenMenu.contactDinaEmail": "dina.kriukova@cainarchive.com",
      "sections.collectionText": "over 100",
      "sections.collectionSubtext": "Documented Photographs",
      "sections.collectionLabel": "collection",
      "sections.pressArticle": "Article",
      "sections.pressDesc1": "Les Petits Cousins D'europe Des Epoux Kennedy",
      "sections.pressDesc2": "Pilgrims to Kennedy's Grave",
      "sections.pressDesc4": "A Flashy Lawyer for Oswald's Killer",
      "sections.pressDesc3": "Le Match Kennedy-Nixon",
      "sections.watchMore": "Watch More",
      "sections.chapterVisionaryTitle": "The Visionary",
      "sections.chapterPresidencyTitle": "The Presidency",
      "sections.chapterLegacyTitle": "The Legacy",
      "sections.galleryNote": "Only part of this collection and its materials is shown. For full access, please contact Cain Archive.",
      "sections.chapterVisionaryText": "Between gesture and silence, between hope and doubt — the human story of vision unfolds. Kennedy was not only seen, he was felt — as light, as voice, as the certainty that tomorrow could begin again.",
      "sections.chapterPresidencyText": "Leadership measured not in words, but in silence. These moments of The Presidency reflect the balance between intellect and responsibility.",
      "sections.chapterLegacyText": "From loss to memory, from memory to meaning.",
      /*Churchill*/
      "sections.collectionSubtext": "Original Photographs",
      "sections.over": "over",
      "sections.galleryNote": "Only part of this collection and its materials is shown. For full access, please contact Cain Archive.",
      "sections.CpressDesc1": "Churchill is 86",
      "sections.CpressDesc2": "Churchill at 90: Twilight of a Hero",
      "sections.navLeader": "The Leader",
      "sections.navPrivateMan": "The Private Man",
      "sections.chapterLeaderTitle": "The Leader and the Visionary",
      "sections.chapterLeaderSubheading": "from War to Peace",
      "sections.chapterLeaderText": "These photographs trace the transformation of a wartime leader into a statesman of peace — a testament to endurance, diplomacy, and the moral courage that defined an age.",
      "sections.chapterPrivateManTitle": "The Private Man and the Legacy",
      "sections.chapterPrivateManText": "A final portrait of Churchill beyond politics — surrounded by family, reflection, and time. From private gardens to public farewells, these photographs capture a man at peace with history — a statesman turned into memory.",
      /*Icons*/
      "coming.title": "Icons & Culture",
      "coming.collection": "collection",
      "coming.soon": "Coming soon...",
   },
   ar: {
      "nav.home": "الصفحة الرئيسية",
      "nav.ww2": "المحرقة والحرب العالمية الثانية",
      "nav.hollywood": "الأيقونات والثقافة",
      "footer.slogan": ["التاريخ الذي يشكل ", "الغد"],
      "footer.founderTitle": "المؤسس والمدير | Cain الأرشيف",
      "footer.coordinatorTitle": "منسقة المؤسسات والأرشيف | Cain الأرشيف",
      "footer.founderEmail": "john@cainarchive.com",
      "footer.founderPhone": "+1 561 884 0648",
      "footer.coordinatorEmail": "dina.kriukova@cainarchive.com",
      "footer.copyright": "© 2025 Cain الأرشيف. جميع الحقوق محفوظة.",
      "footer.protectedText": "يتم عرض الصور الفوتوغرافية الأصلية القديمة لأغراض توثيقية وتعليمية وبحثية. Cain الأرشيف يحتفظ بالملكية المادية للنسخ الأصلية، ولكنه لا يطالب بحقوق الطبع والنشر للصور. يُحظر النسخ أو الاستخدام التجاري غير المصرح به.",
      "fullscreenMenu.home": "الصفحة الرئيسية",
      "fullscreenMenu.ww2": "المحرقة والحرب العالمية الثانية",
      "fullscreenMenu.hollywood": "الأيقونات والثقافة",
      "fullscreenMenu.contactFounderTitle": 'المؤسس والمدير | Cain أرشيف',
      "fullscreenMenu.contactEmail": "john@cainarchive.com",
      "fullscreenMenu.contactPhone": "+1 561 884 0648",
      "fullscreenMenu.contactCoordinatorTitle": "منسقة المؤسسات والأرشيف | Cain الأرشيف",
      "fullscreenMenu.contactDinaEmail": "dina.kriukova@cainarchive.com",
      "sections.collectionText": "أكثر من 100",
      "sections.collectionLabel": "المجموعة",
      "sections.pressArticle": "مقال",
      "sections.collectionSubtext": "صور موثقة",
      "sections.pressArticle": "مقال",
      "sections.pressDesc1": "أبناء عمومة أوروبا الصغار لزوجي Kennedy",
      "sections.pressDesc2": "الحجاج إلى قبر Kennedy",
      "sections.pressDesc4": "محامٍ بارز لقاتل Oswald",
      "sections.pressDesc3": "المباراة بين Kennedy و Nixon",
      "sections.watchMore": "شاهد المزيد",
      "sections.chapterVisionaryTitle": "المبصر",
      "sections.chapterPresidencyTitle": "الرئاسة",
      "sections.chapterLegacyTitle": "الإرث",
      "sections.galleryNote": "يتم عرض جزء فقط من هذه المجموعة وموادها. للوصول الكامل، يرجى الاتصال بـ Cain الأرشيف.",
      "sections.chapterVisionaryText": "بين الإيماءة والصمت، بين الأمل والشك — تتكشف القصة الإنسانية للرؤية. لم يُرَ Kennedy فقط، بل شعر به — كضوء، كصوت، كاليقين بأن الغد يمكن أن يبدأ من جديد.",
      "sections.chapterPresidencyText": "القيادة تُقاس ليس بالكلمات، بل بالصمت. تعكس هذه اللحظات من الرئاسة التوازن بين الفكر والمسؤولية.",
      "sections.chapterLegacyText": "من الفقدان إلى الذاكرة، ومن الذاكرة إلى المعنى.",
      /*Churchill*/
      "sections.collectionSubtext": "صور أصلية",
      "sections.over": "أكثر من",
      "sections.galleryNote": "يتم عرض جزء فقط من هذه المجموعة وموادها. للوصول الكامل، يرجى الاتصال بـ Cain الأرشيف.",
      "sections.CpressDesc1": "Churchill عمره 86 عامًا",
      "sections.CpressDesc2": "Churchill في سن 90: غروب بطل",
      "sections.navLeader": "القائد",
      "sections.navPrivateMan": "الرجل الخاص",
      "sections.chapterLeaderTitle": "القائد والمبصر",
      "sections.chapterLeaderSubheading": "من الحرب إلى السلام",
      "sections.chapterLeaderText": "تتبع هذه الصور تحول قائد الحرب إلى رجل دولة للسلام — شهادة على الصبر والدبلوماسية والشجاعة الأخلاقية التي ميزت عصرًا.",
      "sections.chapterPrivateManTitle": "الرجل الخاص والإرث",
      "sections.chapterPrivateManText": "صورة أخيرة لـChurchill خارج السياسة — محاطًا بالعائلة والتفكير والزمن. من الحدائق الخاصة إلى وداع العامة، تلتقط هذه الصور رجلًا في سلام مع التاريخ — رجل دولة تحول إلى ذكرى.",
      /*Icons*/
      "coming.title": "الأيقونات والثقافة",
      "coming.collection": "المجموعة",
      "coming.soon": "قريباً...",
   },
   ja: {
      "nav.home": "ホーム",
      "nav.ww2": "ホロコーストと第二次世界大戦",
      "nav.hollywood": "アイコンと文化",
      "footer.slogan": ["未来を形作る", "明日"],
      "footer.founderTitle": "創設者兼ディレクター | Cain アーカイブ",
      "footer.coordinatorTitle": "機関・アーカイブコーディネーター | Cain アーカイブ",
      "footer.founderEmail": "john@cainarchive.com",
      "footer.founderPhone": "+1 561 884 0648",
      "footer.coordinatorEmail": "dina.kriukova@cainarchive.com",
      "footer.copyright": "© 2025 Cain アーカイブ. 無断転載禁止。",
      "footer.protectedText": "オリジナルのヴィンテージ写真は、記録・教育・研究目的で展示されています。Cain アーカイブは原本の所有権を有しますが、画像の著作権を主張しません。無断複製・商用利用は禁止されています。",
      "fullscreenMenu.home": "ホーム",
      "fullscreenMenu.ww2": "ホロコーストと第二次世界大戦",
      "fullscreenMenu.hollywood": "アイコンと文化",
      "fullscreenMenu.contactFounderTitle": '創設者兼ディレクター | Cain アーカイブ',
      "fullscreenMenu.contactEmail": "john@cainarchive.com",
      "fullscreenMenu.contactPhone": "+1 561 884 0648",
      "fullscreenMenu.contactCoordinatorTitle": "機関・アーカイブコーディネーター | Cain アーカイブ",
      "fullscreenMenu.contactDinaEmail": "dina.kriukova@cainarchive.com",
      "sections.collectionText": "100以上",
      "sections.collectionLabel": "コレクション",
      "sections.pressArticle": "記事",
      "sections.collectionSubtext": "記録写真",
      "sections.pressArticle": "記事",
      "sections.pressDesc1": "Kennedy夫妻のヨーロッパの小さな親戚",
      "sections.pressDesc2": "Kennedyの墓への巡礼者",
      "sections.pressDesc4": "Oswaldの殺人者の派手な弁護士",
      "sections.pressDesc3": "Kennedy対Nixonの対決",
      "sections.watchMore": "もっと見る",
      "sections.chapterVisionaryTitle": "ビジョナリー",
      "sections.chapterPresidencyTitle": "大統領職",
      "sections.chapterLegacyTitle": "レガシー",
      "sections.galleryNote": "このコレクションとその資料の一部のみが表示されています。完全なアクセスについては、Cain アーカイブにお問い合わせください。",
      "sections.chapterVisionaryText": "ジェスチャーと沈黙の間、希望と疑念の間で — ビジョンの人間的物語が展開されます。Kennedyは見られただけでなく、光として、声として、明日が再び始まるという確信として感じられました。",
      "sections.chapterPresidencyText": "リーダーシップは言葉ではなく沈黙で測られます。大統領職のこれらの瞬間は、知性と責任のバランスを反映しています。",
      "sections.chapterLegacyText": "喪失から記憶へ、記憶から意味へ。",
      /*Churchill*/
      "sections.collectionSubtext": "オリジナル写真",
      "sections.over": "以上",
      "sections.galleryNote": "このコレクションとその資料の一部のみが表示されています。完全なアクセスについては、Cain アーカイブにお問い合わせください。",
      "sections.CpressDesc1": "Churchillは86歳です",
      "sections.CpressDesc2": "Churchill 90歳：英雄の黄昏",
      "sections.navLeader": "リーダー",
      "sections.navPrivateMan": "私的な人",
      "sections.chapterLeaderTitle": "指導者とビジョナリー",
      "sections.chapterLeaderSubheading": "戦争から平和へ",
      "sections.chapterLeaderText": "これらの写真は、戦時の指導者が平和の政治家へと変貌する様子を追っています — 忍耐、外交、そしてその時代を定義した道徳的勇気の証です。",
      "sections.chapterPrivateManTitle": "私的な人と遺産",
      "sections.chapterPrivateManText": "Churchillの政治を超えた最終的なポートレート — 家族、反省、そして時間に囲まれて。私的な庭園から公的な別れまで、これらの写真は歴史と平和の中で過ごす男を捉えています — 政治家から記憶へと変わった男。",
      /*Icons*/
      "coming.title": "アイコンと文化",
      "coming.collection": "コレクション",
      "coming.soon": "近日公開...",
   },
   es: {
      "nav.home": "Inicio",
      "nav.ww2": "Holocausto y Segunda Guerra Mundial",
      "nav.hollywood": "Íconos y Cultura",
      "footer.slogan": ["Historia que da forma al ", "mañana"],
      "footer.founderTitle": "Fundador y Director | Cain Archivo",
      "footer.coordinatorTitle": "Coordinadora Institucional y de Archivo | Cain Archivo",
      "footer.founderEmail": "john@cainarchive.com",
      "footer.founderPhone": "+1 561 884 0648",
      "footer.coordinatorEmail": "dina.kriukova@cainarchive.com",
      "footer.copyright": "© 2025 Cain Archivo. Todos los derechos reservados.",
      "footer.protectedText": "Las fotografías originales se presentan con fines documentales, educativos e investigativos. Cain Archivo posee físicamente las copias originales, pero no reclama derechos de autor sobre las imágenes. Se prohíbe la reproducción o el uso comercial no autorizado.",
      "fullscreenMenu.home": "Inicio",
      "fullscreenMenu.ww2": "Holocausto y Segunda Guerra Mundial",
      "fullscreenMenu.hollywood": "Íconos y Cultura",
      "fullscreenMenu.contactFounderTitle": 'Fundador y Director | Cain Archivo',
      "fullscreenMenu.contactEmail": "john@cainarchive.com",
      "fullscreenMenu.contactPhone": "+1 561 884 0648",
      "fullscreenMenu.contactCoordinatorTitle": "Coordinadora Institucional y de Archivo | Cain Archivo",
      "fullscreenMenu.contactDinaEmail": "dina.kriukova@cainarchive.com",
      "sections.collectionText": "más de 100",
      "sections.collectionLabel": "colección",
      "sections.pressArticle": "Artículo",
      "sections.collectionSubtext": "Fotografías documentadas",
      "sections.pressArticle": "Artículo",
      "sections.pressDesc1": "Los pequeños primos europeos de los esposos Kennedy",
      "sections.pressDesc2": "Peregrinos a la tumba de Kennedy",
      "sections.pressDesc4": "Un abogado llamativo del asesino de Oswald",
      "sections.pressDesc3": "El enfrentamiento Kennedy-Nixon",
      "sections.watchMore": "Ver más",
      "sections.chapterVisionaryTitle": "El Visionario",
      "sections.chapterPresidencyTitle": "La Presidencia",
      "sections.chapterLegacyTitle": "El Legado",
      "sections.galleryNote": "Solo se muestra una parte de esta colección y sus materiales. Para acceder a todo, comuníquese con Cain Archivo.",
      "sections.chapterVisionaryText": "Entre gesto y silencio, entre esperanza y duda — se desarrolla la historia humana de la visión. Kennedy no solo fue visto, sino sentido — como luz, como voz, como la certeza de que mañana podría comenzar de nuevo.",
      "sections.chapterPresidencyText": "El liderazgo no se mide en palabras, sino en silencio. Estos momentos de La Presidencia reflejan el equilibrio entre intelecto y responsabilidad.",
      "sections.chapterLegacyText": "De la pérdida a la memoria, de la memoria al significado.",
      /*Churchill*/
      "sections.collectionSubtext": "Fotografías Originales",
      "sections.over": "más de",
      "sections.galleryNote": "Solo se muestra una parte de esta colección y sus materiales. Para acceder a todo, comuníquese con Cain Archivo.",
      "sections.CpressDesc1": "Churchill tiene 86 años",
      "sections.CpressDesc2": "Churchill a los 90: Crepúsculo de un Héroe",
      "sections.navLeader": "El Líder",
      "sections.navPrivateMan": "El Hombre Privado",
      "sections.chapterLeaderTitle": "El Líder y el Visionario",
      "sections.chapterLeaderSubheading": "De la guerra a la paz",
      "sections.chapterLeaderText": "Estas fotografías trazan la transformación de un líder de guerra en un estadista de paz — un testamento a la resistencia, la diplomacia y el coraje moral que definieron una época.",
      "sections.chapterPrivateManTitle": "El Hombre Privado y el Legado",
      "sections.chapterPrivateManText": "Un retrato final de Churchill más allá de la política — rodeado de familia, reflexión y tiempo. Desde jardines privados hasta despedidas públicas, estas fotografías capturan a un hombre en paz con la historia — un estadista convertido en memoria.",
      /*Icons*/
      "coming.title": "Íconos y Cultura",
      "coming.collection": "colección",
      "coming.soon": "Próximamente...",

   },
   zh: {
      "nav.home": "首页",
      "nav.ww2": "二战与大屠杀",
      "nav.hollywood": "文化与偶像",
      "footer.slogan": ["塑造", "明天"],
      "footer.founderTitle": "创始人兼馆长 | Cain 档案",
      "footer.coordinatorTitle": "机构与档案协调员 | Cain 档案",
      "footer.founderEmail": "john@cainarchive.com",
      "footer.founderPhone": "+1 561 884 0648",
      "footer.coordinatorEmail": "dina.kriukova@cainarchive.com",
      "footer.copyright": "© 2025 Cain 档案 版权所有。",
      "footer.protectedText": "展示的原版老照片仅供文献、教育和研究用途。Cain 档案 拥有原始照片的实物所有权，但不主张图片的版权。禁止未经授权的复制或商业使用。",
      "fullscreenMenu.home": "首页",
      "fullscreenMenu.ww2": "二战与大屠杀",
      "fullscreenMenu.hollywood": "文化与偶像",
      "fullscreenMenu.contactFounderTitle": '创始人兼主任 | Cain 档案馆',
      "fullscreenMenu.contactEmail": "john@cainarchive.com",
      "fullscreenMenu.contactPhone": "+1 561 884 0648",
      "fullscreenMenu.contactCoordinatorTitle": "机构与档案协调员 | Cain 档案",
      "fullscreenMenu.contactDinaEmail": "dina.kriukova@cainarchive.com",
      "sections.collectionText": "超过100",
      "sections.collectionLabel": "收藏",
      "sections.pressArticle": "文章",
      "sections.collectionSubtext": "记录照片",
      "sections.pressArticle": "文章",
      "sections.pressDesc1": "Kennedy夫妇的欧洲小表亲",
      "sections.pressDesc2": "前往Kennedy墓地的朝圣者",
      "sections.pressDesc4": "Oswald杀手的浮夸律师",
      "sections.pressDesc3": "Kennedy-Nixon 对决",
      "sections.watchMore": "查看更多",
      "sections.chapterVisionaryTitle": "远见者",
      "sections.chapterPresidencyTitle": "总统任期",
      "sections.chapterLegacyTitle": "遗产",
      "sections.galleryNote": "仅显示此收藏及其材料的一部分。如需完整访问，请联系 Cain 档案。",
      "sections.chapterVisionaryText": "在动作与沉默之间，在希望与怀疑之间 — 展现了人类的远见故事。Kennedy不仅被看见，更被感受到 — 如光、如声音，如明天可以重新开始的确定性。",
      "sections.chapterPresidencyText": "领导力不是用言语衡量，而是用沉默衡量。这些总统任期的瞬间反映了智慧与责任的平衡。",
      "sections.chapterLegacyText": "从失落到记忆，从记忆到意义。",
      /*Churchill*/
      "sections.collectionSubtext": "原始照片",
      "sections.over": "超过",
      "sections.galleryNote": "仅显示此收藏及其材料的一部分。如需完整访问，请联系 Cain 档案。",
      "sections.CpressDesc1": "Churchill 86岁",
      "sections.CpressDesc2": "Churchill 90岁：英雄的暮光",
      "sections.navLeader": "领导者",
      "sections.navPrivateMan": "私人之人",
      "sections.chapterLeaderTitle": "领导者与梦想家",
      "sections.chapterLeaderSubheading": "从战争到和平",
      "sections.chapterLeaderText": "这些照片追溯了一位战争时期的领导者转变为和平时期的政治家的过程 — 见证了坚韧、外交以及定义一个时代的道德勇气。",
      "sections.chapterPrivateManTitle": "私人之人及遗产",
      "sections.chapterPrivateManText": "Churchill的最后一幅肖像，超越了政治 — 被家人、反思和时间环绕。从私人花园到公共告别，这些照片捕捉到一个与历史和平相处的男人 — 一个转化为记忆的政治家。",
      /*Icons*/
      "coming.title": "文化与偶像",
      "coming.collection": "收藏",
      "coming.soon": "即将推出...",
   }
};

const updateTranslations = (lang) => {
   localStorage.setItem('lang', lang);

   document.querySelectorAll("[data-key]").forEach((el) => {
      const key = el.getAttribute("data-key");

      if (key === "footer.slogan" && Array.isArray(translations[lang][key])) {
         const [before, after] = translations[lang][key];
         const span = el.querySelector("span");

         if (span) {
            span.textContent = after;
            if (el.firstChild) el.firstChild.textContent = before;
         } else {
            el.textContent = `${before}${after}`;
         }
      } else if (translations[lang][key]) {
         el.textContent = translations[lang][key];
      }
   });

   // ( 'EN', 'AR', 'JA')
   const langCurrentSpan = document.getElementById('lang-current');
   if (langCurrentSpan) {
      langCurrentSpan.textContent = lang.toUpperCase();
   }
};

const loadLanguage = () => {
   const savedLang = localStorage.getItem('lang');
   const defaultLang = 'en';
   updateTranslations(savedLang || defaultLang);
};

const languageButtons = document.querySelectorAll('[data-lang]');
languageButtons.forEach((langItem) => {
   langItem.addEventListener('click', (e) => {
      const selectedLang = e.target.getAttribute('data-lang');
      updateTranslations(selectedLang);
   });
});

document.addEventListener('DOMContentLoaded', loadLanguage);