const translations = {
   en: {
      "nav.home": "Home",
      "nav.ww2": "Holocaust & WWII",
      "nav.hollywood": "Icons & Culture",
      "footer.slogan": ["History that shapes ", "Tomorrow"],
      "footer.founderTitle": "Founder & Director | Cain Archive",
      "footer.coordinatorTitle": "Institutional & Archive Coordinator | Cain Archive",
      "footer.founderEmail": "john@cainarchive.com",
      "footer.founderPhone": "+1 561 884 0648",
      "footer.coordinatorEmail": "dina.kriukova@cainarchive.com",
      "footer.copyright": "© 2025 Cain Archive. All Rights Reserved.",
      "footer.protectedText": "Original vintage photographs are displayed for documentary, educational, and research purposes. Cain Archive holds physical ownership of the original prints but does not claim copyright to the underlying images. Unauthorized reproduction or commercial use is prohibited.",
      "fullscreenMenu.home": "Home",
      "fullscreenMenu.ww2": "Holocaust & WWII",
      "fullscreenMenu.hollywood": "Icons & Culture",
      "fullscreenMenu.contactFounderTitle": "Founder & Director | Cain Archive",
      "fullscreenMenu.contactEmail": "john@cainarchive.com",
      "fullscreenMenu.contactPhone": "+1 561 884 0648",
      "fullscreenMenu.contactCoordinatorTitle": "Institutional & Archive Coordinator | Cain Archive",
      "fullscreenMenu.contactDinaEmail": "dina.kriukova@cainarchive.com",
      //Witness
      "wwii.title": "World War II",
      "wwii.collection": "collection",
      "wwii.propaganda": "Propaganda and the Fall of Darkness",
      "wwii.witness": "The Witness and the Silence",
      "wwii.occupation": "From Occupation to Retribution",
      "wwii.ashes": "From Ashes to Legacy",
      "wwii.propagandaLabel": "Propaganda",
      "wwii.heroWitnessTitle": "The Witness and",
      "wwii.heroSilenceTitle": "the Silence",
      "wwii.heroText": "Over 170 authentic photographs trace the silence that followed the shattered world of Europe’s Jews. Each frame is a witness — not only to what was lost, but to the enduring will to be remembered.",
      "wwii.collectionAccess": "Only part of this collection and its materials is shown. For full access, please contact Cain Archive.",
      "eichmann": "Eichmann",
      "terezinBelsen": "Terezin & Belsen",
      "lidiceOradour": "Lidice & Oradour",
      "echoes": "Echoes",
      "witnessSilence": "The Witness and the Silence",
      "eichmannTitle": "Eichmann",
      "crimesEvidence": "Crimes and Evidence",
      "pressPhotosText": "Authentic press photographs and documents trace the moment when horror met accountability. Each image bears silent witness to a truth too vast for one trial — but impossible to forget.",
      "testimonyRetribution": "Testimony and Retribution",
      "campsJusticeText": "From the ruins of the camps arose the language of justice. These photographs capture the first moments when memory turned against oblivion — and truth demanded a voice.",
      "citiesOfSilence": "Cities of Silence",
      "lidiceOradourText": "Two towns — Lidice and Oradour — stand as Europe’s living memorials. Destroyed in 1942 and 1944, they rose again as symbols of survival, justice, and the world’s promise never to forget.",
      "echoesOfHatred": "Echoes of Hatred",
      "damascus1962": "Damascus 1962",
      "nurembergDamascusText": "From Nuremberg to Damascus, the rhetoric of justice became a mirror for hate. These images from 1962 remind us that memory fades faster than fear — and that silence, once again, became the world’s accomplice.",
      // Propaganda
      "propagandaAnd": "Propaganda and",
      "fallOfDarkness": "the Fall of Darkness",
      "warArcText": "The arc of a world at war — from illusion to awakening. A testament to how humanity was deceived, endured, and learned to begin again.",
      "alliedSands": "Allied Sands",
      "TfallOfDarkness": "The Fall of Darkness",
      "warBeganText": "Before the first shot was fired, the war began with persuasion — shaping fear, obedience, and illusion. Truth was twisted, identity erased, and vision trained to see only what power allowed.",
      "northAfricaText": "Across the deserts of North Africa, nations found unity in purpose and endurance. What began as a campaign became a brotherhood — proof that even in war, humanity can rise above conquest.",
      "collapseOfPowerText": "The collapse of power came with both liberation and loss. The world awoke to ruins and silence — a freedom that carried the weight of memory. Much was still to be rebuilt: cities, justice, faith itself.",
      // Occupation
      "fromOccupation": "From Occupation",
      "toRetribution": "to Retribution",
      "retributionText": "Retribution was never a single moment, but a reckoning that spanned decades. Here, history faces its own reflection — in law, in guilt, and in the fading shadow of peace.",
      "auschwitz": "Auschwitz",
      "eichmannTrial": "Eichmann Trial",
      "spandau": "Spandau",
      "auschwitzRevisited": "Auschwitz Revisited",
      "auschwitzRevisitedText": "Two decades after liberation, the ghosts of Auschwitz were summoned once more — this time by law. These images capture the moment when justice returned to the ruins, seeking proof among the ashes.",
      "eichmannTrialPostwarJustice": "Eichmann Trial - Postwar Justice",
      "eichmannTrialText": "In 1961, the trial of Adolf Eichmann transformed a single courtroom into the moral center of the world. These photographs preserve the faces of justice — judges, witnesses, and the accused — when history itself took the stand.",
      "spandauLastPrisoners": "Spandau - the Last Prisoners",
      "spandauSilenceText": "In the silence of Spandau, time itself became their sentence. Justice had been served, yet peace remained uncertain.",
      // Ashes
      "fromAshes": "From Ashes",
      "toLegacy": "to Legacy",
      "fromAshesText": "From ashes, humanity began again — not to forget, but to rebuild meaning. These photographs reveal how memory turned into legacy, and grief into purpose.",
      "lifelongVictims": "Lifelong Victims",
      "rebirthOfANation": "Rebirth of a Nation",
      "rebirthText": "Captured by Paul Almasy, these images document the forgotten aftermath of liberation — survivors who carried the wounds of the Holocaust into the decades that followed. In villages of care and silence, they rebuilt fragments of purpose amid the ruins of memory.",
      "israelNewHumanism": "Israel and the New Humanism",
      "israelNewHumanismText": "From ruins and exile emerged not only a nation — but a new kind of human being. These photographs capture Israel’s birth as a moral and spiritual event, where art, faith, and science converged to give the world a new language of humanity.",

   },
   ar: {
      "nav.home": "الصفحة الرئيسية",
      "nav.ww2": "المحرقة والحرب العالمية الثانية",
      "nav.hollywood": "الأيقونات والثقافة",
      "footer.slogan": ["التاريخ الذي يشكل ", "الغد"],
      "footer.founderTitle": "المؤسس والمدير | Cain الأرشيف",
      "footer.coordinatorTitle": "منسقة المؤسسات والأرشيف | Cain الأرشيف",
      "footer.founderEmail": "john@cainarchive.com",
      "footer.founderPhone": "+1 561 884 0648",
      "footer.coordinatorEmail": "dina.kriukova@cainarchive.com",
      "footer.copyright": "© 2025 Cain الأرشيف. جميع الحقوق محفوظة.",
      "footer.protectedText": "يتم عرض الصور الفوتوغرافية الأصلية القديمة لأغراض توثيقية وتعليمية وبحثية. Cain الأرشيف يحتفظ بالملكية المادية للنسخ الأصلية، ولكنه لا يطالب بحقوق الطبع والنشر للصور. يُحظر النسخ أو الاستخدام التجاري غير المصرح به.",
      "fullscreenMenu.home": "الصفحة الرئيسية",
      "fullscreenMenu.ww2": "المحرقة والحرب العالمية الثانية",
      "fullscreenMenu.hollywood": "الأيقونات والثقافة",
      "fullscreenMenu.contactFounderTitle": 'المؤسس والمدير | Cain أرشيف',
      "fullscreenMenu.contactEmail": "john@cainarchive.com",
      "fullscreenMenu.contactPhone": "+1 561 884 0648",
      "fullscreenMenu.contactCoordinatorTitle": "منسقة المؤسسات والأرشيف | Cain الأرشيف",
      "fullscreenMenu.contactDinaEmail": "dina.kriukova@cainarchive.com",
      //Witness
      "wwii.title": "الحرب العالمية الثانية",
      "wwii.collection": "المجموعة",
      "wwii.propaganda": "الدعاية وسقوط الظلام",
      "wwii.witness": "الشاهد والصمت",
      "wwii.occupation": "من الاحتلال إلى الانتقام",
      "wwii.ashes": "من الرماد إلى الإرث",
      "wwii.propagandaLabel": "الدعاية",
      "wwii.heroWitnessTitle": "الشاهد و",
      "wwii.heroSilenceTitle": "الصمت",
      "wwii.heroText": "تتبع أكثر من 170 صورة فوتوغرافية أصلية الصمت الذي أعقب العالم المدمّر لليهود في أوروبا. كل إطار هو شاهد — ليس فقط على ما فقد، ولكن على الإرادة المستمرة ليتم تذكره.",
      "wwii.collectionAccess": "يتم عرض جزء فقط من هذه المجموعة وموادها. للحصول على الوصول الكامل، يرجى الاتصال بـ Cain الأرشيف.",
      "eichmann": "آيشمان",
      "terezinBelsen": "تيريزين و بيلسن",
      "lidiceOradour": "ليديس و أورادور",
      "echoes": "أصداء",
      "witnessSilence": "الشاهد والصمت",
      "eichmannTitle": "آيشمان",
      "crimesEvidence": "الجرائم والأدلة",
      "pressPhotosText": "تتبع الصور الصحفية الأصلية والوثائق اللحظة التي واجه فيها الرعب المساءلة. كل صورة تشهد بصمت على حقيقة واسعة جدًا لتغطيها محاكمة واحدة — لكنها مستحيلة النسيان.",
      "testimonyRetribution": "الشهادة والانتقام",
      "campsJusticeText": "من بين أنقاض المعسكرات نشأت لغة العدالة. تلتقط هذه الصور اللحظات الأولى التي انقلبت فيها الذاكرة ضد النسيان — وطلبت الحقيقة صوتًا.",
      "citiesOfSilence": "مدن الصمت",
      "lidiceOradourText": "تعتبر مدينتان — ليديس وأورادور — نصبًا حيًا في أوروبا. تم تدميرهما في 1942 و1944، ولكنهما نهضتا مرة أخرى كرموز للبقاء والعدالة ووعد العالم بعدم النسيان.",
      "echoesOfHatred": "أصداء الكراهية",
      "damascus1962": "دمشق 1962",
      "nurembergDamascusText": "من نورمبرغ إلى دمشق، أصبحت خطابات العدالة مرآة للكراهية. تذكرنا هذه الصور من عام 1962 أن الذاكرة تتلاشى أسرع من الخوف — وأن الصمت، مرة أخرى، أصبح متواطئًا للعالم.",
      // Propaganda 
      "propagandaAnd": "الدعاية و",
      "fallOfDarkness": "سقوط الظلام",
      "warArcText": "قوس عالم في حالة حرب — من الوهم إلى اليقظة. شهادة على كيف تم خداع الإنسانية، وصمدت، وتعلمت أن تبدأ من جديد.",
      "alliedSands": "رمال الحلفاء",
      "TfallOfDarkness": "سقوط الظلام",
      "warBeganText": "قبل أن يتم إطلاق الرصاصة الأولى، بدأ الحرب بالإقناع — تشكيل الخوف والطاعة والوهم. تم تشويه الحقيقة، وتم محو الهوية، وتم تدريب الرؤية لرؤية فقط ما سمحت به السلطة.",
      "northAfricaText": "عبر صحاري شمال أفريقيا، وجدت الأمم الوحدة في الهدف والصمود. ما بدأ كحملة أصبح أخوة — دليل على أنه حتى في الحرب، يمكن للإنسانية أن تتجاوز الفتح.",
      "collapseOfPowerText": "جاء انهيار السلطة مع التحرير والخسارة. استيقظ العالم على الخراب والصمت — حرية تحمل عبء الذاكرة. كان هناك الكثير ليُعاد بناءه: المدن، والعدالة، والإيمان نفسه.",
      // Occupation
      "fromOccupation": "من الاحتلال",
      "toRetribution": "إلى الانتقام",
      "retributionText": "لم تكن الانتقام لحظة واحدة، بل كانت حسابًا امتد لعقود. هنا، يواجه التاريخ انعكاسه الخاص — في القانون، في الشعور بالذنب، وفي ظل السلام المتلاشي.",
      "auschwitz": "أوشفيتز",
      "eichmannTrial": "محاكمة أيخمان",
      "spandau": "سبانداو",
      "auschwitzRevisited": "أوشفيتز المعاد زيارته",
      "auschwitzRevisitedText": "بعد عقدين من التحرير، استُدعي أشباح أوشفيتز مرة أخرى — هذه المرة بواسطة القانون. تلتقط هذه الصور اللحظة التي عادت فيها العدالة إلى الخراب، تبحث عن دليل بين الرماد.",
      "eichmannTrialPostwarJustice": "محاكمة أيخمان - العدالة ما بعد الحرب",
      "eichmannTrialText": "في عام 1961، حولت محاكمة Adolf Eichmann قاعة محكمة واحدة إلى مركز أخلاقي للعالم. تحفظ هذه الصور وجوه العدالة — القضاة، والشهود، والمتهمين — عندما مثلت التاريخ نفسه على المنصة.",
      "spandauLastPrisoners": "سبانداو - آخر السجناء",
      "spandauSilenceText": "في صمت سبانداو، أصبح الزمن نفسه حكمهم. لقد تحققت العدالة، لكن السلام ظل غير مؤكد.",
      // Ashes 
      "fromAshes": "من الرماد",
      "toLegacy": "إلى الإرث",
      "fromAshesText": "من الرماد، بدأت الإنسانية من جديد — ليس للنسيان، بل لإعادة بناء المعنى. تكشف هذه الصور كيف تحولت الذاكرة إلى إرث، والحزن إلى هدف.",
      "lifelongVictims": "ضحايا مدى الحياة",
      "rebirthOfANation": "بعث أمة",
      "rebirthText": "توثق هذه الصور التي التقطها Paul Almasy العواقب المنسية للتحرير — الناجون الذين حملوا جراح الهولوكوست عبر العقود التالية. في القرى المليئة بالرعاية والصمت، أعادوا بناء شظايا المعنى وسط أنقاض الذاكرة.",
      "israelNewHumanism": "إسرائيل والإنسانية الجديدة",
      "israelNewHumanismText": "من بين الأنقاض والمنفى نشأت ليس أمة فقط — بل نوع جديد من البشر. تلتقط هذه الصور ميلاد إسرائيل كحدث أخلاقي وروحي، حيث تلاقت الفن والإيمان والعلم لمنح العالم لغة جديدة للإنسانية.",

   },
   ja: {
      "nav.home": "ホーム",
      "nav.ww2": "ホロコーストと第二次世界大戦",
      "nav.hollywood": "アイコンと文化",
      "footer.slogan": ["未来を形作る", "明日"],
      "footer.founderTitle": "創設者兼ディレクター | Cain アーカイブ",
      "footer.coordinatorTitle": "機関・アーカイブコーディネーター | Cain アーカイブ",
      "footer.founderEmail": "john@cainarchive.com",
      "footer.founderPhone": "+1 561 884 0648",
      "footer.coordinatorEmail": "dina.kriukova@cainarchive.com",
      "footer.copyright": "© 2025 Cain アーカイブ. 無断転載禁止。",
      "footer.protectedText": "オリジナルのヴィンテージ写真は、記録・教育・研究目的で展示されています。Cain アーカイブは原本の所有権を有しますが、画像の著作権を主張しません。無断複製・商用利用は禁止されています。",
      "fullscreenMenu.home": "ホーム",
      "fullscreenMenu.ww2": "ホロコーストと第二次世界大戦",
      "fullscreenMenu.hollywood": "アイコンと文化",
      "fullscreenMenu.contactFounderTitle": '創設者兼ディレクター | Cain アーカイブ',
      "fullscreenMenu.contactEmail": "john@cainarchive.com",
      "fullscreenMenu.contactPhone": "+1 561 884 0648",
      "fullscreenMenu.contactCoordinatorTitle": "機関・アーカイブコーディネーター | Cain アーカイブ",
      "fullscreenMenu.contactDinaEmail": "dina.kriukova@cainarchive.com",
      //Witness
      "wwii.title": "第二次世界大戦",
      "wwii.collection": "コレクション",
      "wwii.propaganda": "プロパガンダと闇の崩壊",
      "wwii.witness": "証人と沈黙",
      "wwii.occupation": "占領から報復へ",
      "wwii.ashes": "灰から遺産へ",
      "wwii.propagandaLabel": "プロパガンダ",
      "wwii.heroWitnessTitle": "証人と",
      "wwii.heroSilenceTitle": "沈黙",
      "wwii.heroText": "170点以上の本物の写真が、ヨーロッパのユダヤ人の壊滅的な世界が残した沈黙を辿ります。それぞれの写真は証人です — 失われたものだけでなく、記憶されるべきという不屈の意志の証でもあります。",
      "wwii.collectionAccess": "このコレクションとその資料の一部のみが表示されます。完全なアクセスには、Cain アーカイブにご連絡ください。",
      "eichmann": "アイヒマン",
      "terezinBelsen": "テレジン & ベルゼン",
      "lidiceOradour": "リディツェ & オラドゥール",
      "echoes": "エコーズ",
      "witnessSilence": "証人と沈黙",
      "eichmannTitle": "アイヒマン",
      "crimesEvidence": "犯罪と証拠",
      "pressPhotosText": "本物の報道写真や文書は、恐怖が責任と向き合った瞬間を辿ります。それぞれの画像は、1回の裁判では計り知れない真実を静かに証言しています — しかし忘れることは不可能です。",
      "testimonyRetribution": "証言と報復",
      "campsJusticeText": "収容所の廃墟から正義の言語が生まれました。これらの写真は、記憶が忘却に立ち向かい、真実が声を求めた最初の瞬間を捉えています。",
      "citiesOfSilence": "沈黙の街",
      "lidiceOradourText": "2つの町 — リディツェとオラドゥール — は、ヨーロッパの生きた記念碑として存在します。1942年と1944年に破壊されましたが、生存、正義、そして忘れないという世界の約束の象徴として再び蘇りました。",
      "echoesOfHatred": "憎悪の残響",
      "damascus1962": "ダマスカス 1962",
      "nurembergDamascusText": "ニュルンベルクからダマスカスへ、正義の言説は憎しみの鏡となった。1962年のこれらの画像は、記憶が恐怖よりも速く薄れていくこと、そして沈黙が再び世界の共犯者となったことを私たちに思い出させます。",
      // Propaganda 
      "propagandaAnd": "プロパガンダと",
      "fallOfDarkness": "闇の崩壊",
      "warArcText": "戦争の世界の弧 — 幻想から覚醒へ。人類がどのように欺かれ、耐え、そして再び始めることを学んだかの証です。",
      "alliedSands": "連合軍の砂",
      "TfallOfDarkness": "闇の崩壊",
      "warBeganText": "最初の銃声が響く前に、戦争は説得から始まりました — 恐怖、服従、そして幻想を形作ることから。真実は歪められ、アイデンティティは消され、視覚は力が許すものだけを見るように訓練されました。",
      "northAfricaText": "北アフリカの砂漠を越えて、国々は目的と忍耐において団結を見出しました。キャンペーンとして始まったものが兄弟愛となり — 戦争の中でも人間性が征服を超えることができる証です。",
      "collapseOfPowerText": "権力の崩壊は解放と喪失の両方を伴いました。世界は廃墟と沈黙に目覚めました — 記憶の重みを伴う自由。再建すべきものは多くありました：都市、正義、そして信仰そのもの。",
      // Occupation
      "fromOccupation": "占領から",
      "toRetribution": "報復へ",
      "retributionText": "報復は一瞬の出来事ではなく、何十年にもわたる清算でした。ここで歴史は自らの反映と向き合います — 法の中で、罪の中で、そして薄れる平和の影の中で。",
      "auschwitz": "アウシュヴィッツ",
      "eichmannTrial": "アイヒマン裁判",
      "spandau": "スパンダウ",
      "auschwitzRevisited": "アウシュヴィッツ再訪",
      "auschwitzRevisitedText": "解放から二十年後、アウシュヴィッツの幽霊は再び呼び起こされました — 今度は法によって。これらの画像は、正義が廃墟に戻り、灰の中で証拠を求めた瞬間を捉えています。",
      "eichmannTrialPostwarJustice": "アイヒマン裁判 - 戦後の正義",
      "eichmannTrialText": "1961年、Adolf Eichmannの裁判は、1つの法廷を世界の道徳的中心に変えました。これらの写真は、正義の顔 — 裁判官、証人、そして被告 — が歴史そのものが証言台に立った瞬間を保存しています。",
      "spandauLastPrisoners": "スパンダウ - 最後の囚人",
      "spandauSilenceText": "スパンダウの静寂の中で、時間そのものが彼らの刑となった。正義は果たされたが、平和はまだ不確かであった。",
      // Ashes 
      "fromAshes": "灰から",
      "toLegacy": "遺産へ",
      "fromAshesText": "灰から、人類は再び始まりました — 忘れるためではなく、意味を再構築するために。これらの写真は、記憶がどのように遺産に変わり、悲しみが目的に変わったかを明らかにします。",
      "lifelongVictims": "生涯の犠牲者",
      "rebirthOfANation": "国家の再生",
      "rebirthText": "Paul Almasyが捉えたこれらの写真は、解放後の忘れられた影響を記録しています — ホロコーストの傷をその後の数十年に持ち続けた生存者たち。ケアと静寂の村で、彼らは記憶の廃墟の中で目的の断片を再構築しました。",
      "israelNewHumanism": "イスラエルと新しい人文主義",
      "israelNewHumanismText": "廃墟と亡命の中から生まれたのは、単なる国家ではなく、新しい種類の人間でした。これらの写真は、イスラエルの誕生を道徳的かつ精神的な出来事として捉え、芸術、信仰、科学が融合して世界に新たな人間性の言語を与えた瞬間を記録しています。",

   },

   es: {
      "nav.home": "Inicio",
      "nav.ww2": "Holocausto y Segunda Guerra Mundial",
      "nav.hollywood": "Íconos y Cultura",
      "footer.slogan": ["Historia que da forma al ", "mañana"],
      "footer.founderTitle": "Fundador y Director | Cain Archivo",
      "footer.coordinatorTitle": "Coordinadora Institucional y de Archivo | Cain Archivo",
      "footer.founderEmail": "john@cainarchive.com",
      "footer.founderPhone": "+1 561 884 0648",
      "footer.coordinatorEmail": "dina.kriukova@cainarchive.com",
      "footer.copyright": "© 2025 Cain Archivo. Todos los derechos reservados.",
      "footer.protectedText": "Las fotografías originales se presentan con fines documentales, educativos e investigativos. Cain Archivo posee físicamente las copias originales, pero no reclama derechos de autor sobre las imágenes. Se prohíbe la reproducción o el uso comercial no autorizado.",
      "fullscreenMenu.home": "Inicio",
      "fullscreenMenu.ww2": "Holocausto y Segunda Guerra Mundial",
      "fullscreenMenu.hollywood": "Íconos y Cultura",
      "fullscreenMenu.contactFounderTitle": 'Fundador y Director | Cain Archivo',
      "fullscreenMenu.contactEmail": "john@cainarchive.com",
      "fullscreenMenu.contactPhone": "+1 561 884 0648",
      "fullscreenMenu.contactCoordinatorTitle": "Coordinadora Institucional y de Archivo | Cain Archivo",
      "fullscreenMenu.contactDinaEmail": "dina.kriukova@cainarchive.com",
      //Witness
      "wwii.title": "Segunda Guerra Mundial",
      "wwii.collection": "colección",
      "wwii.propaganda": "Propaganda y la Caída de la Oscuridad",
      "wwii.witness": "El Testigo y el Silencio",
      "wwii.occupation": "De la Ocupación a la Represalia",
      "wwii.ashes": "De las Cenizas al Legado",
      "wwii.propagandaLabel": "Propaganda",
      "wwii.heroWitnessTitle": "El Testigo y",
      "wwii.heroSilenceTitle": "el Silencio",
      "wwii.heroText": "Más de 170 fotografías auténticas siguen el silencio que siguió al mundo destrozado de los judíos de Europa. Cada imagen es un testigo, no solo de lo que se perdió, sino de la voluntad perdurable de ser recordado.",
      "wwii.collectionAccess": "Solo se muestra una parte de esta colección y sus materiales. Para obtener acceso completo, comuníquese con Cain Archivo.",
      "eichmann": "Eichmann",
      "terezinBelsen": "Terezin y Belsen",
      "lidiceOradour": "Lidice y Oradour",
      "echoes": "Ecos",
      "witnessSilence": "El Testigo y el Silencio",
      "eichmannTitle": "Eichmann",
      "crimesEvidence": "Crímenes y Evidencia",
      "pressPhotosText": "Fotografías y documentos auténticos de prensa rastrean el momento en que el horror se encontró con la rendición de cuentas. Cada imagen es testigo silencioso de una verdad demasiado vasta para un solo juicio — pero imposible de olvidar.",
      "testimonyRetribution": "Testimonio y Represalia",
      "campsJusticeText": "De las ruinas de los campos surgió el lenguaje de la justicia. Estas fotografías capturan los primeros momentos en que la memoria se volvió contra el olvido — y la verdad exigió una voz.",
      "citiesOfSilence": "Ciudades del Silencio",
      "lidiceOradourText": "Dos pueblos — Lidice y Oradour — se erigen como memoriales vivos de Europa. Destruidos en 1942 y 1944, resurgieron como símbolos de supervivencia, justicia y la promesa del mundo de no olvidar jamás.",
      "echoesOfHatred": "Ecos del Odio",
      "damascus1962": "Damasco 1962",
      "nurembergDamascusText": "Desde Nuremberg hasta Damasco, la retórica de la justicia se convirtió en un espejo del odio. Estas imágenes de 1962 nos recuerdan que la memoria se desvanece más rápido que el miedo — y que el silencio, una vez más, se convirtió en cómplice del mundo.",
      // Propaganda 
      "propagandaAnd": "Propaganda y",
      "fallOfDarkness": "la Caída de la Oscuridad",
      "warArcText": "El arco de un mundo en guerra — de la ilusión al despertar. Un testamento de cómo la humanidad fue engañada, soportó y aprendió a comenzar de nuevo.",
      "alliedSands": "Arenas Aliadas",
      "TfallOfDarkness": "La caída de la oscuridad",
      "warBeganText": "Antes de que se disparara el primer tiro, la guerra comenzó con persuasión — moldeando el miedo, la obediencia y la ilusión. La verdad fue distorsionada, la identidad borrada, y la visión entrenada para ver solo lo que el poder permitía.",
      "northAfricaText": "A través de los desiertos del norte de África, las naciones encontraron unidad en el propósito y la resistencia. Lo que comenzó como una campaña se convirtió en una hermandad — una prueba de que incluso en la guerra, la humanidad puede superar la conquista.",
      "collapseOfPowerText": "El colapso del poder vino acompañado tanto de liberación como de pérdida. El mundo despertó entre ruinas y silencio — una libertad que llevaba el peso de la memoria. Mucho aún debía ser reconstruido: ciudades, justicia, la fe misma.",
      // Occupation
      "fromOccupation": "Desde la Ocupación",
      "toRetribution": "a la Represalia",
      "retributionText": "La represalia nunca fue un solo momento, sino un ajuste de cuentas que abarcó décadas. Aquí, la historia se enfrenta a su propio reflejo — en la ley, en la culpa y en la sombra que se desvanece de la paz.",
      "auschwitz": "Auschwitz",
      "eichmannTrial": "Juicio a Eichmann",
      "spandau": "Spandau",
      "auschwitzRevisited": "Auschwitz Revisitado",
      "auschwitzRevisitedText": "Dos décadas después de la liberación, los fantasmas de Auschwitz fueron convocados una vez más — esta vez por la ley. Estas imágenes capturan el momento en que la justicia regresó a las ruinas, buscando pruebas entre las cenizas.",
      "eichmannTrialPostwarJustice": "Juicio a Eichmann - Justicia de la posguerra",
      "eichmannTrialText": "En 1961, el juicio de Adolf Eichmann transformó una sola sala de tribunal en el centro moral del mundo. Estas fotografías preservan los rostros de la justicia — jueces, testigos y el acusado — cuando la historia misma subió al estrado.",
      "spandauLastPrisoners": "Spandau - los Últimos Prisioneros",
      "spandauSilenceText": "En el silencio de Spandau, el tiempo mismo se convirtió en su condena. Se había hecho justicia, pero la paz seguía siendo incierta.",
      // Ashes 
      "fromAshes": "De las Cenizas",
      "toLegacy": "al Legado",
      "fromAshesText": "De las cenizas, la humanidad comenzó de nuevo — no para olvidar, sino para reconstruir el significado. Estas fotografías revelan cómo la memoria se convirtió en legado, y el dolor en propósito.",
      "lifelongVictims": "Víctimas de por Vida",
      "rebirthOfANation": "Renacimiento de una Nación",
      "rebirthText": "Capturadas por Paul Almasy, estas imágenes documentan las secuelas olvidadas de la liberación — sobrevivientes que llevaron las heridas del Holocausto durante las décadas siguientes. En pueblos de cuidado y silencio, reconstruyeron fragmentos de propósito entre las ruinas de la memoria.",
      "israelNewHumanism": "Israel y el Nuevo Humanismo",
      "israelNewHumanismText": "De las ruinas y el exilio surgió no solo una nación — sino un nuevo tipo de ser humano. Estas fotografías capturan el nacimiento de Israel como un evento moral y espiritual, donde el arte, la fe y la ciencia convergieron para darle al mundo un nuevo lenguaje de humanidad.",

   },

   zh: {
      "nav.home": "首页",
      "nav.ww2": "二战与大屠杀",
      "nav.hollywood": "文化与偶像",
      "footer.slogan": ["塑造", "明天"],
      "footer.founderTitle": "创始人兼馆长 | Cain 档案",
      "footer.coordinatorTitle": "机构与档案协调员 | Cain 档案",
      "footer.founderEmail": "john@cainarchive.com",
      "footer.founderPhone": "+1 561 884 0648",
      "footer.coordinatorEmail": "dina.kriukova@cainarchive.com",
      "footer.copyright": "© 2025 Cain 档案 版权所有。",
      "footer.protectedText": "展示的原版老照片仅供文献、教育和研究用途。Cain 档案 拥有原始照片的实物所有权，但不主张图片的版权。禁止未经授权的复制或商业使用。",
      "fullscreenMenu.home": "首页",
      "fullscreenMenu.ww2": "二战与大屠杀",
      "fullscreenMenu.hollywood": "文化与偶像",
      "fullscreenMenu.contactFounderTitle": '创始人兼主任 | Cain 档案馆',
      "fullscreenMenu.contactEmail": "john@cainarchive.com",
      "fullscreenMenu.contactPhone": "+1 561 884 0648",
      "fullscreenMenu.contactCoordinatorTitle": "机构与档案协调员 | Cain 档案",
      "fullscreenMenu.contactDinaEmail": "dina.kriukova@cainarchive.com",
      //Witness
      "wwii.title": "第二次世界大战",
      "wwii.collection": "收藏",
      "wwii.propaganda": "宣传与黑暗的陨落",
      "wwii.witness": "见证与沉默",
      "wwii.occupation": "从占领到清算",
      "wwii.ashes": "从灰烬到遗产",
      "wwii.propagandaLabel": "宣传",
      "wwii.heroWitnessTitle": "见证与",
      "wwii.heroSilenceTitle": "沉默",
      "wwii.heroText": "超过170张真实的照片描绘了随欧洲犹太人世界的破碎后产生的沉默。每一张照片都是见证——不仅是对失去的东西，也是对永恒的记忆的坚持。",
      "wwii.collectionAccess": "仅显示此收藏及其部分资料。欲获取完整访问，请联系 Cain 档案馆。",
      "eichmann": "艾希曼",
      "terezinBelsen": "特雷津与贝尔森",
      "lidiceOradour": "利季采与奥拉杜尔",
      "echoes": "回响",
      "witnessSilence": "见证与沉默",
      "eichmannTitle": "艾希曼",
      "crimesEvidence": "犯罪与证据",
      "pressPhotosText": "真实的新闻照片和文件记录了恐怖与责任交汇的瞬间。每一幅图像都是对一个审判无法覆盖的巨大真相的无声见证——但永远无法被遗忘。",
      "testimonyRetribution": "证词与清算",
      "campsJusticeText": "从集中营的废墟中诞生了正义的语言。这些照片捕捉了记忆对抗遗忘的最初时刻——真相要求被发声。",
      "citiesOfSilence": "沉默的城市",
      "lidiceOradourText": "两个城镇——利季采与奥拉杜尔——作为欧洲的活纪念而存在。它们分别在1942年和1944年被毁，但再次崛起，成为生存、正义以及世界永不忘记的象征。",
      "echoesOfHatred": "仇恨的回响",
      "damascus1962": "大马士革 1962",
      "nurembergDamascusText": "从纽伦堡到大马士革，正义的言辞成为了仇恨的镜子。1962年的这些图片提醒我们，记忆比恐惧消逝得更快——而沉默，再一次，成为了世界的同谋。",
      // Propaganda 
      "propagandaAnd": "宣传与",
      "fallOfDarkness": "黑暗的陨落",
      "warArcText": "战争世界的弧线 — 从幻觉到觉醒。见证人类如何被欺骗、坚持，并学会重新开始。",
      "alliedSands": "盟军之沙",
      "TfallOfDarkness": "黑暗的陨落",
      "warBeganText": "在第一枪响起之前，战争以说服开始 — 塑造恐惧、服从和幻觉。真相被扭曲，身份被抹去，视野被训练只看见权力允许的事物。",
      "northAfricaText": "穿越北非的沙漠，各国在目标和坚持中找到了团结。最初作为一场战役开始的，最终成为了兄弟情谊 — 证明了即使在战争中，人类也能超越征服。",
      "collapseOfPowerText": "权力的崩溃伴随着解放和失落。世界在废墟与沉默中觉醒 — 一种承载记忆重负的自由。仍有许多需要重建的：城市、正义，乃至信仰本身。",
      // Occupation
      "fromOccupation": "从占领开始",
      "toRetribution": "走向清算",
      "retributionText": "清算从不是一个单一的时刻，而是跨越数十年的审判。在这里，历史面对自身的倒影 — 在法律中，在罪恶中，以及在逐渐消逝的和平阴影中。",
      "auschwitz": "奥斯维辛",
      "eichmannTrial": "艾希曼审判",
      "spandau": "斯潘道",
      "auschwitzRevisited": "奥斯维辛重访",
      "auschwitzRevisitedText": "在解放二十年后，奥斯维辛的幽灵再次被召唤 — 这一次是由法律。那些图像捕捉到了正义回到废墟时的瞬间，在灰烬中寻找证据。",
      "eichmannTrialPostwarJustice": "艾希曼审判 - 战后正义",
      "eichmannTrialText": "1961年，Adolf Eichmann的审判将一个法庭转变为世界的道德中心。这些照片保存了正义的面孔 — 法官、证人和被告 — 当历史本身站上证人席时。",
      "spandauLastPrisoners": "斯潘道 - 最后的囚犯",
      "spandauSilenceText": "在斯潘道的沉寂中，时间本身成了他们的刑期。正义已经得到伸张，但和平仍不确定。",
      //Ashes
      "fromAshes": "从灰烬中",
      "toLegacy": "走向遗产",
      "fromAshesText": "从灰烬中，人类重新开始 — 不是为了遗忘，而是为了重建意义。这些照片揭示了记忆如何转化为遗产，悲伤如何转化为目标。",
      "lifelongVictims": "终生受害者",
      "rebirthOfANation": "国家重生",
      "rebirthText": "由 Paul Almasy 拍摄的这些图像记录了解放后的被遗忘后果——幸存者将大屠杀的创伤带入随后的几十年。在关怀与寂静的村庄中，他们在记忆的废墟中重建了目标的碎片。",
      "israelNewHumanism": "以色列与新的人文主义",
      "israelNewHumanismText": "从废墟与流亡中诞生的，不仅是一个国家——还有一种新型的人类。这些照片记录了以色列作为一次道德与精神事件的诞生，在这里，艺术、信仰与科学汇聚，为世界带来了人类的新语言。",
   },
};
const updateTranslations = (lang) => {
   localStorage.setItem('lang', lang);

   document.querySelectorAll("[data-key]").forEach((el) => {
      const key = el.getAttribute("data-key");

      if (key === "footer.slogan" && Array.isArray(translations[lang][key])) {
         const [before, after] = translations[lang][key];
         const span = el.querySelector("span");

         if (span) {
            span.textContent = after;
            if (el.firstChild) el.firstChild.textContent = before;
         } else {
            el.textContent = `${before}${after}`;
         }
      } else if (translations[lang][key]) {
         el.textContent = translations[lang][key];
      }
   });

   // ( 'EN', 'AR', 'JA')
   const langCurrentSpan = document.getElementById('lang-current');
   if (langCurrentSpan) {
      langCurrentSpan.textContent = lang.toUpperCase();
   }
};

const loadLanguage = () => {
   const savedLang = localStorage.getItem('lang');
   const defaultLang = 'en';
   updateTranslations(savedLang || defaultLang);
};

const languageButtons = document.querySelectorAll('[data-lang]');
languageButtons.forEach((langItem) => {
   langItem.addEventListener('click', (e) => {
      const selectedLang = e.target.getAttribute('data-lang');
      updateTranslations(selectedLang);
   });
});

document.addEventListener('DOMContentLoaded', loadLanguage);